### ISSUE TITLE
Teaspoon not working using CodeShip?

### ISSUE THREAD

**Issue by darbs** [modeset/teaspoon#347] opened 2015-04-15 15:14 UTC
I am pretty sure i am doing something wrong but not sure as to what yet.

I can run teaspoon fine locally using the cli ```bundle exec rake teaspoon```. However when the specs attempt to run via CodeShip using the same command, it cannot seem to find my assets. I keep getting the error:

```
# route is in spec_helper.js
Error: ActionView::Template::Error: couldn't find file '../../app/assets/javascripts/blah/Blah'
```

Not sure if this is a codeship error or teaspoon either.

**Comment by mikepack** [comment] 2015-04-16 19:15
What is the actual JavaScript file that can't be loaded (in place of `blah/Blah`)? Is it a teaspoon requirement or one of your app's requirements?

**Comment by jejacks0n** [comment] 2015-04-16 22:11
My guess is that it's not in the precompile list?

**Comment by mikepack** [comment] 2015-04-21 15:23
Going to close this. Will happily reopen if you can provide more insight into the actual file names.

**Comment by darbs** [comment] 2015-04-21 16:48
Im sorry but why are the filenames relevant? I could name them ```blah/Blah.js``` the issue is still valid.

I also have them in my pre compile list.
```
Rails.application.config.assets.precompile += %w( blah/Blah.js )
```

In my gemfile
```
group :development, :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'factory_girl_rails'
  gem 'teaspoon', '~> 0.9.0'
  gem 'mocha'
  gem 'selenium-webdriver'
end
```

```
# commands ran on codeship
rvm use 2.1.1
bundle install
bundle exec rake db:migrate
bundle exec rake assets:precompile
export RAILS_ENV=test
bundle exec rake db:schema:load

bundle exec rake teaspoon
```

I also see ```Using teaspoon 0.9.1``` when codeship ran bundle install.

**Comment by mikepack** [comment] 2015-04-21 17:09
The file names are important so I can distinguish whether your setup is having trouble loading a teaspoon JS file or your application's JS file.

Can you paste the portion of your code that requires `blah/Blah.js`?

**Closed** 2015-04-27 18:14 UTC

**Comment by laserlemon** [comment] 2016-02-12 14:24
I'm having a similar problem and it seems to be due to the "sprockets" gem version. Locally, everything works with sprockets 2.12.4 but the build server has 3.5.2 installed. For me this can happen because `Gemfile.lock` is not checked in since I'm developing a gem so the build server fetches the latest version of sprockets that will satisfy the requirement.

I've confirmed that in my scenario, the jump from 2.12.4 (the last 2.x version) to 3.0.0 (the first 3.0 version) is enough to trigger the error.

**Comment by jejacks0n** [comment] 2016-02-12 16:04
That's fixed in latest.

---
Jeremy Jackson

**Comment by laserlemon** [comment] 2016-02-12 16:14
Latest what?

**Comment by jejacks0n** [comment] 2016-02-12 16:49
Release of teaspoon perhaps? The repo you opened this issue on... :)

---
Jeremy Jackson
