### ISSUE TITLE
Can't load fixtures when running from command line

### ISSUE THREAD

**Issue by jaredmoody** [modeset/teaspoon#435] opened 2015-11-25 00:08 UTC
I'm having trouble running teaspoon on the command line at all, while everything is great in the browser:

```
> teaspoon -v
1.1.1

> teaspoon
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:63423/teaspoon/default
FUnable to load fixture "books.html".
/Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/formatter/base.rb:148:in `filename': undefined method `split' for nil:NilClass (NoMethodError)
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/formatter/modules/report_module.rb:13:in `block in log_error'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/formatter/modules/report_module.rb:11:in `each'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/formatter/modules/report_module.rb:11:in `log_error'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/formatter/base.rb:54:in `error'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/runner.rb:29:in `block in notify_formatters'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/runner.rb:29:in `each'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/runner.rb:29:in `notify_formatters'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/runner.rb:16:in `process'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:28:in `block in run_specs'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:35:in `each'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:35:in `block in run'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:35:in `popen'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:35:in `run'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:27:in `run_specs'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:55:in `run_specs'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:44:in `block in execute_without_handling'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:42:in `each'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:42:in `inject'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:42:in `execute_without_handling'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:27:in `execute'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:23:in `failures?'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/lib/teaspoon/command_line.rb:15:in `initialize'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/bin/teaspoon:6:in `new'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/teaspoon-1.1.1/bin/teaspoon:6:in `<top (required)>'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jaredmoody/Sites/albumexposure/albumexposure.com/bin/teaspoon:7:in `<top (required)>'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/jaredmoody/.gem/ruby/2.2.3/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/jaredmoody/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/jaredmoody/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

`books.html` exists and is at `spec/javascripts/fixtures`, and that fixture path is specified in my `teaspoon_env.rb`:

Here's my full `teaspoon_env.rb`

```
Teaspoon.configure do |config|
  config.mount_at = "/teaspoon"
  config.root = nil
  config.asset_paths = ["spec/javascripts", "spec/javascripts/stylesheets"]
  config.fixture_paths = ["spec/javascripts/fixtures"]

  config.suite do |suite|
    suite.use_framework :mocha, "2.3.3"
    suite.matcher = "{spec/javascripts,app/assets}/**/*_spec.{js,js.coffee,coffee}"
    suite.helper = "spec_helper"
    suite.boot_partial = "boot"
    suite.body_partial = "body"
  end
end
```

I don't know if it's related, but I can't run them via rake either:

```
> rake teaspoon                                                                                                 ruby-2.2.3
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:63519/teaspoon/default
ReferenceError: Can't find variable: Teaspoon
  # /teaspoon/default?reporter=Console:13 -- global code

ReferenceError: Can't find variable: Teaspoon
  # /teaspoon/default?reporter=Console:99 -- global code

Failed to load: http://127.0.0.1:63519/teaspoon/default?reporter=Console
rake teaspoon failed
```

`RAILS_ENV=test rake teaspoon` also yields the `Unable to load fixture` failure.

**Comment by mikepack** [comment] 2015-11-25 17:17
@jaredmoody thanks for reporting this bug. I'll try to spend some turkey time looking into it.

**Comment by elad-maimon** [comment] 2015-11-30 10:16
I have the same issue for quite a time actually.
One thing I noticed is that it happens only when I'm using phantomjs. If I switch to selenium it works.

Another wired symptom, which I'm not sure if it's related or not but may help, is that although I have only 25 tests in the file, when running from CLI it shows 68 tests (some are repeated). On the web UI or in the CLI with selenium it shows 25.

**Comment by mikepack** [comment] 2015-12-06 21:52
@jaredmoody can you confirm this isn't related to any of the issues here? https://github.com/modeset/teaspoon/search?q=Can%27t+find+variable%3A+Teaspoon&type=Issues&utf8=%E2%9C%93

**Comment by jaredmoody** [comment] 2015-12-11 01:59
@mikepack I don't think so. The only cases that seemed like it might the same were the issues with assets, but I don't have an asset host in the test environment and both `RAILS_ENV=test teaspoon` and `RAILS_ENV=test rake teaspoon` fail with the same "undefined method Split" error. 

I may be having one of those issues as well in the development environment, but looks like a different issue in test environment to me.

**Comment by estebanz01** [comment] 2016-01-04 21:09
+1 Here. I found that if I use phantomjs version 2.0, I got the same error reported here:
```bash
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:55531/teaspoon/default
swfobject failed to load to vhlarccontainer_content
Unable to load fixture "activity_item_player.html".
  # teaspoon-jasmine1.js:268
/home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/formatter/base.rb:148:in `filename': undefined method `split' for nil:NilClass (NoMethodError)
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/formatter/modules/report_module.rb:13:in `block in log_error'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/formatter/modules/report_module.rb:11:in `each'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/formatter/modules/report_module.rb:11:in `log_error'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/formatter/base.rb:54:in `error'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/runner.rb:29:in `block in notify_formatters'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/runner.rb:29:in `each'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/runner.rb:29:in `notify_formatters'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/runner.rb:16:in `process'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:28:in `block in run_specs'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:35:in `each'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:35:in `block in run'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:35:in `popen'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:35:in `run'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/driver/phantomjs.rb:27:in `run_specs'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:55:in `run_specs'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:44:in `block in execute_without_handling'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:42:in `each'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:42:in `inject'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:42:in `execute_without_handling'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:27:in `execute'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/console.rb:23:in `failures?'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/lib/teaspoon/command_line.rb:15:in `initialize'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/bin/teaspoon:6:in `new'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/gems/teaspoon-1.1.1/bin/teaspoon:6:in `<top (required)>'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/bin/teaspoon:19:in `load'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/bin/teaspoon:19:in `<main>'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/bin/ruby_executable_hooks:15:in `eval'
        from /home/ezapata/.rvm/gems/ruby-1.9.3-p545-railsexpress@mae/bin/ruby_executable_hooks:15:in `<main>'
```

but if I change phantomjs to 1.9.8, spec runs as expected:
```bash
Starting the Teaspoon server...
Teaspoon running default suite at http://127.0.0.1:41005/teaspoon/default
SyntaxError: Parse error

swfobject failed to load to vhlarccontainer_content
.....

Finished in 0.13200 seconds
5 examples, 0 failures
```

**Comment by Coaxial** [comment] 2016-01-13 16:59
I ran into this issue and here is what I found:

It seems the issue lies somewhere with PhantomJS. This is a binary of phantomjs 2.0.0 from a machine where `rake teaspoon` worked: http://s000.tinyupload.com/index.php?file_id=42632369713235520993 (sorry for the host, feel free to check the file for viruses before running it).

This binary is not the latest phantomjs 2.0. If I install the latest with `brew install phantomjs`, it says it installs 2.0.1 although `phantomjs -v` still outputs `2.0.0`. Anyway, with the latest 2.0, the fixtures can't be loaded just like in this issue. But if you drop the binary linked above in `/usr/local/Cellar/phantomjs/2.0.1/bin/` and run `rake teaspoon` again, everything works fine.

**Comment by estebanz01** [comment] 2016-01-13 17:04
When you put the binay in `.../phantomjs/2.0.1/bin` are you really sure that `teaspoon` is using that phantom version @Coaxial ?

**Comment by Coaxial** [comment] 2016-01-13 17:10
There is no other `phantomjs` binary installed on my machine so if it uses phantomjs at all, it would have to be the binary in that directory

**Comment by Coaxial** [comment] 2016-01-13 19:36
I did check, I searched the whole filesystem for a `phantomjs` binary and the only one coming up is the one installed by brew that I replaced with the version I linked above.

Besodes, using the installed `phantomjs` in its 2.0.1 version from the brew command triggers the problem discussed in this issue. Replacing the binary with the one linked above lets teaspoon run without issues.

**Comment by jejacks0n** [comment] 2016-01-14 15:37
So it sounds like a problem when phantomjs 2.0.1? That's helpful. I'll update and see if it's reproducible, and see if it's resolvable. Thanks. For now, I'd say use 2.0.0 if that's working correctly.

---
Jeremy Jackson

**Comment by Coaxial** [comment] 2016-01-14 16:54
I can't get `2.0.0` to compile on OS X 10.11, and the `2.0.0` from the official website doesn't uncompress with `upx` following their instructions. I give up, I'll just drop in the binary from tinyupload for now.

**Comment by jejacks0n** [comment] 2016-01-14 18:08
well, it's clearly not a teaspoon issue directly, but I'll still try to figure it out.

if you have npm installed, consider `sudo npm -g install phantomjs2` as an alternative.. looks like brew is failing, but npm just installs the binary precompiled.

**Comment by estebanz01** [comment] 2016-01-14 19:15
I built the phantomjs from source in Ubuntu and tested. Indeed is the 2.0.0 version with teaspoon in 1.1.1. I'll try later with 1.1.2 to see what would happen.

**Comment by jejacks0n** [comment] 2016-01-14 19:23
2.0.0, or 2.0.1?

**Comment by estebanz01** [comment] 2016-01-14 19:25
the latest tag version of phantom is 2.0.0 https://github.com/ariya/phantomjs/tags https://github.com/ariya/phantomjs/blob/master/src/consts.h#L38

**Comment by estebanz01** [comment] 2016-01-14 19:37
I got the following output when updated to teaspoon 1.1.2

```bash
Unable to load fixture "activity_item_player.html".
  # teaspoon-jasmine1.js:268
  # :0 -- send
  # teaspoon-jasmine1.js:357 -- xhrRequest
  # teaspoon-jasmine1.js:263 -- load
  # teaspoon-jasmine1.js:217 -- load
  # teaspoon-jasmine1.js:1215 -- load
  # relative_path/to/spec_with_fixture.js:14
  # jasmine/1.3.1.js:1066 -- execute
  # jasmine/1.3.1.js:2098 -- next_
  # jasmine/1.3.1.js:2051 -- start
  # jasmine/1.3.1.js:2378 -- execute
  # jasmine/1.3.1.js:2098 -- next_
  # jasmine/1.3.1.js:2051 -- start
  # jasmine/1.3.1.js:2523 -- execute
  # jasmine/1.3.1.js:2098 -- next_
  # jasmine/1.3.1.js:2094 -- onComplete
  # jasmine/1.3.1.js:2480 -- finish
  # jasmine/1.3.1.js:2524
  # jasmine/1.3.1.js:2108 -- next_
  # jasmine/1.3.1.js:2094 -- onComplete
  # jasmine/1.3.1.js:2480 -- finish
  # jasmine/1.3.1.js:2524
  # jasmine/1.3.1.js:2108 -- next_
  # jasmine/1.3.1.js:2094 -- onComplete
  # jasmine/1.3.1.js:2480 -- finish
  # jasmine/1.3.1.js:2524
  # jasmine/1.3.1.js:2108 -- next_
  # jasmine/1.3.1.js:2088
```

**Comment by jejacks0n** [comment] 2016-01-14 19:39
ah, I wonder if something changed about the XHR implementation or something.. ugg. browsers.

**Comment by Coaxial** [comment] 2016-01-14 20:07
I think the `2.0.1` version is a fix by @Vitallium for compiling issues with `brew`: https://github.com/Vitallium/phantomjs/releases/tag/2.0.1 so users still have a phantomjs option when running El Capitan and waiting for `2.1`.

**Comment by estebanz01** [comment] 2016-01-14 21:53
I just compiled from source https://github.com/Vitallium/phantomjs/releases/tag/2.0.1 and this error, for me in Ubuntu, still happening.

**Comment by jaredmoody** [comment] 2016-01-15 01:30
FWIW I'm getting this error with phantomjs 2.0.0

**Comment by Coaxial** [comment] 2016-01-15 01:37
`phantomjs -v` isn't reliable, it says 2.0.0 for both 2.0.0 and 2.0.1

On January 14, 2016 8:30:28 PM EST, Jared Moody <notifications@github.com> wrote:
>FWIW I'm getting this error with phantomjs 2.0.0
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/modeset/teaspoon/issues/435#issuecomment-171837964

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Vitallium** [comment] 2016-01-15 06:13
Hi guys. Someone mentioned me in a comment. PhantomJS dev here.

I found the problem yesterday. And can confirm that the problem is in AJAX requests.
New feature for capturing the content of requests sometimes breaks AJAX requests. It removes the body and status codes.

I'll fix it ASAP.

Thanks!

**Comment by jejacks0n** [comment] 2016-01-15 06:51
That's great, thanks so much for checking in and resolving it!

---
Jeremy Jackson

**Comment by estebanz01** [comment] 2016-01-15 13:14
Thanks! That's awesome! :+1:

**Comment by Coaxial** [comment] 2016-01-15 14:54
Thanks!

**Comment by jejacks0n** [comment] 2016-01-15 17:52
I'm closing this, as it will probably be resolved shortly and will only effect a small amount of people who have installed the version where ajax isn't behaving. Thanks everybody for the info, and thanks @Vitallium for checking in before I had to really dig into it. =)

**Closed by jejacks0n** 2016-01-15 17:52 UTC
